sudo: false
language: node_js
branches:
    only:
        - master
        - develop
node_js:
  - "6"
install:
  - npm install -g eslint
  - npm install
notifications:
    email:
        - sebastien.decamme@gmail.com
